crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('create/', views.create, name='create'),
    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('myarticle/', views.myarticle, name= 'my_article'),
    path('<int:id>/comment_delete', views.comment_delete, name = 'comment_delete'),
    path('else_board/', views.else_board, name = 'else_board'),
    path('Backjoon_board/', views.Backjoon_board, name = 'Backjoon_board'),
    path('SWEA_board/', views.SWEA_board, name = 'SWEA_board'),
    path('Programmers_board/', views.Programmers_board, name = 'Programmers_board'),
    path('<int:id>/comment_2/', views.comment_2, name = 'comment_2')
]

crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
]

crud/articles/models.py
from urllib import request
from django.db import models

# Create your models here.
class ArticleModel(models.Model):
    variety_1 = (
              ('Backjoon', 'Backjoon'),
              ('SWEA', 'SWEA'),
              ('Programmers', 'Programmers'),
              ('else', 'else'),
    )
    username = models.CharField(max_length=30)
    title = models.CharField(max_length= 30)
    content = models.TextField()
    release_date = models.DateField(auto_now = True)
    update_date = models.DateField(auto_now_add= True)
    variety = models.CharField(max_length=30, choices=variety_1)
    visited = models.IntegerField(default=0)

class CommentModel(models.Model):
    article = models.ForeignKey(ArticleModel, on_delete=models.CASCADE)
    username = models.CharField(max_length=30, default="Please write")
    comment = models.TextField()
    create_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateField(auto_now = True)

class CommentModel_2(models.Model):
    article = models.ForeignKey(CommentModel, on_delete=models.CASCADE)
    username = models.CharField(max_length=30, default="Please write")
    comment = models.TextField()
    create_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)

crud/articles/forms.py
from csv import excel
from dataclasses import field
from django import forms
from .models import ArticleModel, CommentModel, CommentModel_2

class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = ArticleModel
        fields = '__all__'

class CommentForm(forms.ModelForm):
    
    # def __init__(self, *args, **kwargs):
    #     super(CommentForm, self).__init__(*args, **kwargs)
    #     self.fields['comment'].strip = False
    class Meta:
        model = CommentModel
        fields = "__all__"
        exclude = ('article','username')

class Comment2Form(forms.ModelForm):
    class Meta:
        model = CommentModel_2
        fields = "__all__"
        exclude = ("artile",'username')

crud/articles/views.py
from django.shortcuts import render, redirect
from .models import ArticleModel, CommentModel
from .forms import ArticleForm, CommentForm, Comment2Form

# Create your views here.
def home(request):
    articles = ArticleModel.objects.all()
    comments = CommentModel.objects.all()
    N = len(articles)
    new_articles = []
    comments_dic = {}
    for i in range(N):
        article = articles[i]
        comments = CommentModel.objects.filter(article = article)
        new_articles.append((article,len(comments),N-i))
    
    print(new_articles)
    context = {
        "articles" : new_articles,
    }
    return render(request, 'articles/home.html', context)

# 상세 페이지
def detail(request, id):
    article = ArticleModel.objects.get(id = id)
    article.visited = article.visited + 1
    article.save() # 방문수를 계산하기 위해서 조회수를 저장해둔다.
    comment_articles = CommentModel.objects.filter(article = article)
    if request.user.is_authenticated and request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            print(comment)
            comment.article = article
            comment.username = request.user.username
            comment.save()
            return redirect("articles:detail", article.id)
    else:
        comment_form = CommentForm()
    context = {
        "article" : article,
        "comment_form" : comment_form,
        "comment_articles" : comment_articles,
    }
    return render(request, "articles/detail.html", context)
    
def create(request):
    if not request.user.is_authenticated:
        return redirect("articles:home")
    
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False) # commit=False는 Form에서 값만 가져오고 실제 저장은 안되게끔 한다.
            same = ArticleModel.objects.filter(title = post.title)
            if len(same) >= 1:
                context = {
                    "same" : True,
                    "form" : form
                }
                return render(request, "articles/create.html", context)
            
            form.save()
            return redirect("articles:home")
    else:
        form = ArticleForm(initial={'username':request.user.username})
    context = {
        "form" : form
    }
    return render(request, "articles/create.html", context)

def delete(request, id):
    article = ArticleModel.objects.get(id = id)
    article.delete()
    return redirect("articles:home")

# 개인게시판
def myarticle(request):
    articles = ArticleModel.objects.filter(username = request.user.username)
    context = {
        'articles' : articles
    }
    
    return render(request, "articles/myarticle.html", context)

def comment_delete(request, id):
    comment = CommentModel.objects.get(id = id)
    comment.delete()
    return redirect("articles:detail", comment.article.id) # comment.article을 외부키로 뒀기 때문에 같이 삭제되는 것 같다.

# 여기서부터는 종류별로 페이지 호출하는 함수
def else_board(request):
    articles = ArticleModel.objects.filter(variety = "else")
    context = {
        "articles" : articles
    }
    return render(request, "articles/else_board.html", context)

def Backjoon_board(request):
    articles = ArticleModel.objects.filter(variety = "Backjoon")
    context = {
        "articles" : articles
    }
    return render(request, "articles/Backjoon_board.html", context)

def SWEA_board(request):
    articles = ArticleModel.objects.filter(variety = "SWEA")
    context = {
        "articles" : articles
    }
    return render(request, "articles/SWEA_board.html", context)

def Programmers_board(request):
    articles = ArticleModel.objects.filter(variety = "Programmers")
    context = {
        "articles" : articles
    }
    return render(request, "articles/Programmers_board.html", context)

# 대댓글을 달 수 있도록 하는 기능 => detail page에서 만들어야하는데?
def comment_2(request, id):
    if not request.user.is_authenticated:
        return redirect("articles:home")
    
    if request.method == "POST":
        pass
    else:
        form = Comment2Form(initial={'username':request.user.username})
    context = {
        'form' : form
    }
    return render(request, "articles/Programmers_board.html")

crud/articles/templates/articles/Backjoon_board.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group border border-4 my-5">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <h1>백준 게시판</h1>
      <span class="badge badge-primary badge-pill mx-5"><a href="{% url 'articles:create' %}">CREATE</a></span>
    </li>
</ul>
<ul class="list-group">
    {% for article in articles %}
    {% if request.user.is_superuser or request.user.username == article.username%}
    <a href="{% url 'articles:delete' article.id %}"> delete </a>
    {% endif %}
    <a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
    <li class="list-group-item list-group-item-action">
    <div class="container text-center">
        <div class="row">
            <div class="col-6 text-start">{{article.title}}</div>
            <div class="col-2">{{article.username}}</div>
            <div class="col-2">{{article.variety}}</div>
            <div class="col-2">{{article.release_date}}</div>
        </div>
    </div>
    </li>
    </a>
    {% endfor %}
</ul>
{% endblock content %}

crud/articles/templates/articles/Programmers_board.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group border border-4 my-5">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <h1>프로그래머스 게시판</h1>
      <span class="badge badge-primary badge-pill mx-5"><a href="{% url 'articles:create' %}">CREATE</a></span>
    </li>
</ul>
<ul class="list-group">
    {% for article in articles %}
    {% if request.user.is_superuser or request.user.username == article.username%}
    <a href="{% url 'articles:delete' article.id %}"> delete </a>
    {% endif %}
    <a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
    <li class="list-group-item list-group-item-action">
    <div class="container text-center">
        <div class="row">
            <div class="col-6 text-start">{{article.title}}</div>
            <div class="col-2">{{article.username}}</div>
            <div class="col-2">{{article.variety}}</div>
            <div class="col-2">{{article.release_date}}</div>
        </div>
    </div>
    </li>
    </a>
    {% endfor %}
</ul>
{% endblock content %}

crud/articles/templates/articles/SWEA_board.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group border border-4 my-5">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <h1>SWEA 게시판</h1>
      <span class="badge badge-primary badge-pill mx-5"><a href="{% url 'articles:create' %}">CREATE</a></span>
    </li>
</ul>
<ul class="list-group">
    {% for article in articles %}
    {% if request.user.is_superuser or request.user.username == article.username%}
    <a href="{% url 'articles:delete' article.id %}"> delete </a>
    {% endif %}
    <a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
    <li class="list-group-item list-group-item-action">
    <div class="container text-center">
        <div class="row">
            <div class="col-6 text-start">{{article.title}}</div>
            <div class="col-2">{{article.username}}</div>
            <div class="col-2">{{article.variety}}</div>
            <div class="col-2">{{article.release_date}}</div>
        </div>
    </div>
    </li>
    </a>
    {% endfor %}
</ul>
{% endblock content %}

crud/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
{% if same %}
같은 제목을 쓰지 마시오.
{% endif %}
<form action="{% url 'articles:create' %}" method = "POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        Submit
      </button>
    {% endbuttons %}
</form>
{% endblock content %}

crud/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load markdown_deux_tags %}

{% block content %}
<nav id="navbar-example2" class="navbar px-3 mb-3">
    <a class="navbar-brand" href="#">{{article.title}}</a>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <span class="nav-link text-dark">{{article.username}}</span>
      </li>
      <li class="nav-item">
        <span class="nav-link text-dark">{{article.release_date}}</span>
      </li>
      <li class="nav-item">
        <span class="nav-link text-dark">조회 수 : {{article.visited}}</span>
      </li>
    </ul>
</nav>
<div data-bs-spy="scroll" class="scrollspy-example bg-light p-3 rounded-2 my-3" tabindex="0">
  <div>{{article.content|markdown|linebreaks}}</div>
</div>
<h2 class='my-5'>댓글</h2>
{% for comment_article in comment_articles %}
{% if request.user.username == comment_article.username %}
<a href="{% url 'articles:comment_delete' comment_article.id %}">delete</a>
{% endif %}
<nav id="navbar-example2" class="navbar bg-light px-3 mb-3">
  <pre>
    {{comment_article.comment|markdown|linebreaks}}
    <a href="{% url 'articles:comment_2' comment_article.id %}" class='text-decoration-none text-black'>댓글달기</a>
  </pre>
  <ul class="nav nav-pills">
    <li class="nav-item mx-5">
      {{comment_article.username}}
    </li>
    <li class="nav-item mx-5">
      {{comment_article.create_at}}
    </li>
  </ul>
</nav>
{% endfor %}
{% if request.user.is_authenticated %}
<form action="{% url 'articles:detail' article.id %}" method="POST" class="form">
  {% csrf_token %}
  {% bootstrap_form comment_form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>
{% endif %}
{% endblock content %}

crud/articles/templates/articles/else_board.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group border border-4 my-5">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <h1>자유 게시판</h1>
      <span class="badge badge-primary badge-pill mx-5"><a href="{% url 'articles:create' %}">CREATE</a></span>
    </li>
</ul>
<ul class="list-group">
    {% for article in articles %}
    {% if request.user.is_superuser or request.user.username == article.username%}
    <a href="{% url 'articles:delete' article.id %}"> delete </a>
    {% endif %}
    <a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
    <li class="list-group-item list-group-item-action">
    <div class="container text-center">
        <div class="row">
            <div class="col-6 text-start">{{article.title}}</div>
            <div class="col-2">{{article.username}}</div>
            <div class="col-2">{{article.variety}}</div>
            <div class="col-2">{{article.release_date}}</div>
        </div>
    </div>
    </li>
    </a>
    {% endfor %}
</ul>
{% endblock content %}

crud/articles/templates/articles/home.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group border border-4 my-5">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <h1>전체게시판</h1>
      {% if request.user.is_active %}
      <span class="badge badge-primary badge-pill mx-5"><a href="{% url 'articles:create' %}">게시글 작성하기</a></span>
      {% endif %}
    </li>
</ul>

<ul class="list-group">
    {% for article, comments, number in articles reversed %}
    {% if request.user.is_superuser or request.user.username == article.username%}
    <div class='my-2'><a href="{% url 'articles:delete' article.id %}" class='bg-secondary rounded text-white mx-3 px-2 text-decoration-none'> delete </a></div>
    {% endif %}
    <a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
    <li class="list-group-item list-group-item-action">
    <div class="container text-center">
        <div class="row">
            <div class="col-1 text-start">{{number}}</div>              
            <div class="col-6 text-start">{{article.title}}
                [{{comments}}]
                {% if comments >= 5 %}
                <span class='bg-secondary rounded text-white mx-3 px-2'>추천</span>
                {% endif %}
            </div>
            <div class="col-1">{{article.username}}</div>
            <div class="col-1">{{article.variety}}</div>
            <div class="col-2">{{article.release_date}}</div>
        </div>
    </div>
    </li>
    </a>
    {% endfor %} 
    <div>if you want more information : <a href="{% url 'articles:else_board' %}" class='text-decoration-none text-success'>자유게시판</a>, <a href="{% url 'articles:Backjoon_board' %}" class='text-decoration-none text-success'>Backjoon</a>,
       <a href="{% url 'articles:SWEA_board' %}" class='text-decoration-none text-success'>SWEA</a>, <a href="{% url 'articles:Programmers_board' %}" class='text-decoration-none text-success'>Programmers</a> </div>
</ul>
{% endblock content %}

crud/articles/templates/articles/myarticle.html
{% extends 'base.html' %}

{% block content %}

<hr>
<h1 class='my-5'>Backjoon</h1>
<hr>
<ul class="list-group">
{% for article in articles %}
{% if article.variety == "Backjoon" %}
<a href="{% url 'articles:delete' article.id %}">delete</a>
<a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
    <li class="list-group-item list-group-item-action">
    <div class="container text-center">
        <div class="row">
            <div class="col-6 text-start">{{article.title}}</div>
            <div class="col-2">{{article.username}}</div>
            <div class="col-2">{{article.variety}}</div>
            <div class="col-2">{{article.release_date}}</div>
        </div>
    </div>
    </li>
</a>
{% endif %}
{% endfor %}
</ul>

<hr>
<h1 class='my-5'>SWEA</h1>
<hr>
<ul class="list-group">
{% for article in articles %}
{% if article.variety == "SWEA" %}
<a href="{% url 'articles:delete' article.id %}">delete</a>
<a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
    <li class="list-group-item list-group-item-action">
    <div class="container text-center">
        <div class="row">
            <div class="col-6 text-start">{{article.title}}</div>
            <div class="col-2">{{article.username}}</div>
            <div class="col-2">{{article.variety}}</div>
            <div class="col-2">{{article.release_date}}</div>
        </div>
    </div>
    </li>
</a>
{% endif %}
{% endfor %}
</ul>

<hr>
<h1 class='my-5'>Programmers</h1>
<hr>
{% for article in articles %}
{% if article.variety == "Programmers" %}
<a href="{% url 'articles:delete' article.id %}">delete</a>
<ul class="list-group">
    <a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
        <li class="list-group-item list-group-item-action">
        <div class="container text-center">
            <div class="row">
                <div class="col-6 text-start">{{article.title}}</div>
                <div class="col-2">{{article.username}}</div>
                <div class="col-2">{{article.variety}}</div>
                <div class="col-2">{{article.release_date}}</div>
            </div>
        </div>
        </li>
    </a>
</ul>
{% endif %}
{% endfor %}

<hr>
<h1 class='my-5'>기타 잡담</h1>
<hr>
{% for article in articles %}
{% if article.variety == "else" %}
<a href="{% url 'articles:delete' article.id %}">delete</a>
<ul class="list-group">
    <a href="{% url 'articles:detail' article.id %}" class='text-decoration-none'>
        <li class="list-group-item list-group-item-action">
        <div class="container text-center">
            <div class="row">
                <div class="col-6 text-start">{{article.title}}</div>
                <div class="col-2">{{article.username}}</div>
                <div class="col-2">{{article.variety}}</div>
                <div class="col-2">{{article.release_date}}</div>
            </div>
        </div>
        </li>
    </a>
</ul>
{% endif %}
{% endfor %}

{% endblock content %}