mypjt/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    
]

mypjt/login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.login , name='login'),
    path('verify/', views.verify, name='verify'), # 반드시 다른 url을 만들어줘야한다.
    path('joinmembership/', views.joinmembership, name='joinmembership'),
    path('create/', views.create, name = 'create'),
]

mypjt/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path('', views.index, name = "index"),
    path('create/', views.create, name = 'create'),
    path('<int:id>', views.detail, name = 'detail'),
    path('<int:id>/update', views.update, name = 'update'),
    path('<int:id>/delete', views.delete, name = 'delete')
]

mypjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', include('login.urls')),
    path('accounts/', include('accounts.urls')),
]

mypjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

mypjt/movies/models.py
from django.db import models

# Create your models here.
class movies_info(models.Model):
    genre_list = [("공포", "공포"),("스릴러", "스릴러"),("액션", "액션"),("드라마", "드라마")]
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release = models.DateField()
    genre = models.CharField(max_length=30, choices=genre_list)
    score = models.FloatField()
    poster_url = models.TextField()
    sub_description = models.TextField(default='aa')
    description = models.TextField()

mypjt/login/forms.py
# HTML에서 forms를 django form으로 만드는 과정
from django import forms
from .models import Login


# HTML안에 넣어주면서 조회만 하는 경우에는 Form을 사용한다.
class LoginForm(forms.Form):
    id = forms.CharField()
    password = forms.CharField()

class plusForm(forms.ModelForm):
    # 변수 이름과 fields 안에 있는 변수 이름이 같아야 매칭 된다.
    verify_id = forms.CharField(
        label='아이디',
        # 단순히 input tag의 표현정도를 조절만 한다.
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control', # 여기서 bootstrap을 사용
                'placeholder' : 'Write ID',
                'maxlength' : 10,
            }
        ),
        error_messages= {
            'required' : 'Please enter your id'
        }
    )
    
    password = forms.CharField(
        label='비밀번호',
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : 'Write password',
                'maxlength' : 10,
            }
        ),
        error_messages= {
            'required' : 'Please enter your password'
        }
    )
    class Meta:
        model = Login
        fields = "__all__"
        

mypjt/movies/forms.py
from django import forms
from .models import movies_info

# 그냥 form으로 만드는 경우
# class NewForm(forms.Form):
#     class Meta:
#         model = movies_info
#         fields = '__all__'
#         exclude = ('title',)
#     genre_list = [("공포", "공포"),("스릴러", "스릴러"),("액션", "액션"),("드라마", "드라마")]
#     title = forms.CharField()
#     audience = forms.IntegerField()
#     release_date = forms.DateField()
#     genre = forms.ChoiceField(choices=genre_list)
#     score = forms.DecimalField()
#     poster_url = forms.URLField()
#     description = forms.CharField(widget = forms.Textarea)

# ModelForm 자체를 가져오는 경우
class NewForm(forms.ModelForm):
    
    class Meta:
        model = movies_info
        fields = '__all__'
        

mypjt/login/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from . import models
from . import forms
# Create your views here.
def login(request):
    form = forms.LoginForm()
    context = {
        'form' : form
    }
    return render(request, 'login/login.html', context)

def verify(request):
    keys = request.POST.keys()
    print(keys)
    # id와 password를 가져온다.
    Dic = {}
    for key in keys:
        Dic[key] = request.POST.get(key)
    print(Dic['id'], Dic['password'])
    # model의 database에서 해당 id/password가 있는지 확인한다.
    database = models.Login.objects.filter(verify_id = Dic['id'], password = Dic['password'])
    print(database)
    if len(database) >= 1: # 만약 있다면
        return redirect("movies:index")
    else: # 없다면
        return redirect("login:login")

# 데이터베이스 자체를 조작해야하는 경우에는 MODEFORM으로 사용
def joinmembership(request):
    form = forms.plusForm()
    context = {
        "form" : form
    }
    return render(request, "login/joinmemebership.html", context)

def create(request):
    form = forms.plusForm(request.POST)
    print(form)
    if form.is_valid():
        form.save() # 그냥 해당 form을 해도 저장이 된다?
        return redirect('login:login')
    return redirect('login:joinmembership')

mypjt/movies/views.py
from django.shortcuts import render, redirect
from . import models
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from . import forms
# Create your views here.
@require_safe # GET인 요청에 대해서만 사용 => POST로 넘기면 405
def index(request):
    object = models.movies_info.objects.all() #데이터 변경이 없으므로 조회(GET)임
    context = {
        "articles" : object
    }
    return render(request, 'index.html', context)


@require_http_methods(['GET','POST'])
# 생성한 데이터를 저장하는 함수
def create(request):
    if request.method == "POST": # 이미 만들어진 HTML FORM에서 작성해서 서버로 보낸다면
        form = forms.NewForm(request.POST) # Model에 있는 각각의 값을 호출한다.
        if form.is_valid(): # 전부 다 제대로 입력이 되었다면
            article = form.save() # 해당 자료를 저장한다. => Modelform이기 때문에 가능
            return redirect("movies:detail", article.id) # detail page로 가자
    else: # 입력해서 보내준 것이 아니라면 
        form = forms.NewForm() # 새로운 Form을 가져오기

    print(f"Error : {form.errors}")
    context = {
        "form" : form,
    }
    return render(request, "create.html", context) # create.html로 넘어가기

# 개별적으로 나타내는 것
def detail(request, id):
    article = models.movies_info.objects.get(id = id)
    print(article.title)
    context ={
        "article" : article
    }
    return render(request, "detail.html", context)

#업데이트
@require_http_methods(['GET','POST'])
def update(request, id):
    article = models.movies_info.objects.get(id=id)
    if request.method == "POST":
        form = forms.NewForm(request.POST, instance=article) 
        # instance : 
        if form.is_valid():
            form.save()
            return redirect("movies:index")
    else:
        form = forms.NewForm(instance=article)
    context = {
        'form' : form,
        'article' : article,
    }
    return render(request, 'update.html', context)

# 삭제함수
@require_POST # POST일 때만 사용하게끔 한다. => POST??? 
def delete(request, id):
    article = models.movies_info.objects.get(id = id)
    article.delete()
    return redirect('movies:index')

mypjt/login/templates/login/joinmemebership.html
{% extends 'base.html' %}

{% block content %}
<h1 class='text-center'>회원가입</h1>
<form action='{% url 'login:create' %}' method = 'POST'>
  {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<a href="{% url 'login:login' %}"><button type="submit" class="btn btn-primary">Back</button></a>
{% endblock content %}

mypjt/login/templates/login/login.html
{% extends 'base.html' %}

{% block content %}
    <form action='{% url 'login:verify' %}' method = 'POST'>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">로그인하기</button>
    </form>
    <a href="{% url 'login:joinmembership' %}"><button class="btn btn-primary">회원가입</button></a>
{% endblock content %}

mypjt/movies/templates/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<h2>Bootstrap v-5 사용</h2>
<form action='{% url 'movies:create' %}' method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">Submit </button>
  {% endbuttons %}
</form>

{% endblock content %}

mypjt/movies/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class='text-center'>
<img src="{{article.poster_url}}" alt="image" width='500'>
</div>
<h1 class='text-center my-5'>줄거리</h1>
<hr>
<div class='text-center'>
  <b>{{article.title}}</b> <br>
  Audience : {{article.audience}} <br>
  Release Dates : {{article.release}} <br>
  Genre : {{article.genre}} <br>
  Score : {{article.score}} <br><br><br>
  {{article.description}} <br>
  <ul class="nav justify-content-center my-3">
    <li class="nav-item">
      <a href="{% url 'movies:update' article.id %}" class="nav-link">EDIT</a> 
    </li>
    <li class="nav-item">
      <a href="{% url 'movies:delete' article.id %}" class="nav-link text-danger">DELETE</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'movies:index' %}" class="nav-link">BACK</a>
    </li>
  </ul>
{% endblock content %}

mypjt/movies/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container alert alert-success">
  <h1 class='text-center my-3'>상영중인 영화</h1>
  <div class='text-center'>
    <a href="{% url 'movies:create' %}" class="text-decoration-none text-dark">영화 추가하기</a> 
  </div>
</div>
{% for article in articles reversed %}
  <div class="container text-center">
    <div class="row my-5">
      <div class="col">
        <img src="{{article.poster_url}}" alt="image" width='400'>
      </div>
      <div class="col">
        <hr>
        <h1>{{article.title}}</h1>
        <div class='my-3 fs-5'>
          
         평점 : <b>{{article.score}}</b>
        </div>
        <div class='my-3 fs-5'>
        출시일자 : {{article.release}}
        </div>
        <div class='my-3 fs-5'>
        장르  :    {{article.genre}}
        </div>
        <div class='my-3 fs-6'>
          간략한 줄거리 : {{article.sub_description}}
        </div>
        <a href="{% url 'movies:detail' article.id %}">
          <button class="btn btn-primary">자세히 보기</button>
        </a>
      </div>
    <div>
  </div>
{% endfor %}
{% endblock content %}

mypjt/movies/templates/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<hr>
{{article.title}}
<form action='{% url 'movies:update' article.id %}' method = 'POST'>
  {% csrf_token %}
    {{form.as_p}}
    <button type="reset" class="btn btn-primary">Reset</button>
    <button type="submit" class="btn btn-primary">submit</button>
</form>
<hr>
<a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

mypjt/mypjt/templates/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    <div class='mx-5 my-5'>
    {% block content %}
    
    {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>