crud/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('index/', views.index, name = 'index'),
    path('create/', views.create, name = 'create'),
    path('<int:id>/update/', views.update, name = 'update'),
    path('<int:id>/delete/', views.delete, name = 'delete'),
    path('logout/', views.logout, name = 'logout'),
    path('<int:id>/password/', views.change_password, name = 'change_password'),
]

crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
]

crud/accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

crud/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm # Substitute 생성 함수
from django.contrib.auth import get_user_model # from .models import User를 직접 참조하지 않기 위해서 django에서 만든 함수

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta): # 상위 Meta를 상속받아서
        model = get_user_model() # Substitute Database를 들고온다.
        fields =  UserCreationForm.Meta.fields + ('email','date_joined')

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username','email')

crud/accounts/views.py
import re
from django.shortcuts import render, redirect
from .models import User
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout # 실제 세션을 만드는 함수

# Create your views here.
def login(request): 
    if request.user.is_authenticated:
        return redirect("accounts:index")

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("articles:home")
    else:
        form = AuthenticationForm()
    context = {
        "form" : form
    }
    return render(request, 'accounts/login.html', context)

def index(request):
    database = User.objects.all()  # 쿼리셋
    print(request.user)
    context = {
        "database" : database
    }
    return render(request, 'accounts/index.html', context)

def create(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:home')
    else:
        form = CustomUserCreationForm()
    context = {
        "form" : form
    }
    return render(request, 'accounts/create.html', context)

def update(request, id):
    if request.method == "POST":
        if request.user.is_superuser == 1:
            user = User.objects.get(id=id)
        if request.user.is_superuser == 0:
            user = request.user
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
        if request.user.is_superuser:
            return redirect("accounts:index")
        else:
            return redirect("articles:home")
    else:
        if request.user.is_superuser == 1:
            user = User.objects.get(id=id)
        if request.user.is_superuser == 0:
            user = request.user
        form = CustomUserChangeForm(instance=user)
    context = {
        'form' : form
    }

    return render(request, 'accounts/update.html', context)

def delete(request,id):
    if request.user.is_superuser == 1:
        user = User.objects.get(id=id)
    if request.user.is_superuser == 0:
        user = request.user
    user.delete()
    auth_logout(request) # 세션 자체를 없애고 싶을 때
    return redirect('accounts:login')

def logout(request):
    auth_logout(request)
    return redirect('articles:home')

def change_password(request, id):
    if request.user.is_superuser == 1:
        user = User.objects.get(id=id)
    if request.user.is_superuser == 0:
        user = request.user

    if request.method == "POST":
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            # update_session_auth_hash(request, form.user) # 로그인상태를 유지하는 상태
        return redirect('accounts:index')
    else:
        form = PasswordChangeForm(user)
        id = id
    context = {
        "form" : form,
        "id" : id
    }
    return render(request, 'accounts/change_password.html', context)

crud/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호변경</h1>
<form action="{% url 'accounts:change_password' id %}" method = "POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock content %}

crud/accounts/templates/accounts/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<form action="#" method="POST" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

{% endblock content %}

crud/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_superuser == 1 %}
<h1 class='text-center'>관리자님 사이트에 들어온 것을 환영합니다.</h1>
<h2 class='text-center'>여기는 유저 정보 사이트입니다.</h2>
<hr>
{% endif %}

{% if request.user.is_superuser == 1 %}
  {% for data in database %}
    {% if data.is_superuser == 1 %}
      <h1 class='text-center'>관리자 정보</h1>
      <hr>
      <p class='text-center'> ADMIN ID : {{data.username}} </p>
      <p class='text-center'> ADMIN EMAIL : {{data.email}} </p>
      <p class='text-center'> ADMIN DATE : {{data.date_joined}} </p>
    {% endif %}
  {% endfor %}
  <br><br><br><br>
  <h1 class='text-center'>회원정보</h1>
  {% for data in database %}
    {% if data.is_superuser == 0 %}
      <hr>
      <p class='text-center'> USER ID : {{data.username}} </p>
      <p class='text-center'> USER EMAIL : {{data.email}} </p>
      <p class='text-center'> USER DATE : {{data.date_joined}} </p>
      <p class='text-center'>
        <a href="{% url 'accounts:update' data.id %}">변경하기</a>
        <a href="{% url 'accounts:delete' data.id %}">삭제하기</a>
      </p>
    {% endif %}
  {% endfor %}
{% endif %}

{% if request.user.is_superuser == 0 %}
  <h1>회원정보</h1>
  {% for data in database %}
      <hr>
      USER ID : {{data.username}} <br>
      USER EMAIL : {{data.email}} <br>
      USER DATE : {{data.date_joined}}
      {% if request.user.username == data.username %}
      <a href="{% url 'accounts:update' data.id %}">변경하기</a>
      <a href="{% url 'accounts:delete' data.id %}">삭제하기</a>
      {% endif %}
  {% endfor %}
{% endif %}

{% endblock content %}

crud/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block login_content %}
<form action="#" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value = "로그인하기" class='bg-warning border-warning border border-1'>
  <a href="{% url 'accounts:create' %}" class='text-decoration-none text-dark'>회원가입하기</a>
</form>
{% endblock login_content %}

crud/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<form action="#" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value = "수정하기">
</form>

{% endblock content %}